- type: sectorService
  id: PirateBounties
  components:
  - type: SectorPirateBountyDatabase

- type: sectorService
  id: MailMetrics
  components:
  - type: SectorLogisticStats

 # A global source of character records (DNA, fingerprints, criminal records, etc.)
- type: sectorService
  id: SectorRecords
  components:
  - type: StationRecords
